# #####################################################################
# Automatically generated by qmake (2.01a) czw. lut 12 15:43:30 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    window.cpp
HEADERS += window.h

CONFIG += wwwidgets
