..\kjvdatagen\kjvdatagen book GEN    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_01_GEN.csv
..\kjvdatagen\kjvdatagen book EXOD   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_02_EXOD.csv
..\kjvdatagen\kjvdatagen book LEV    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_03_LEV.csv
..\kjvdatagen\kjvdatagen book NUM    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_04_NUM.csv
..\kjvdatagen\kjvdatagen book DEUT   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_05_DEUT.csv
..\kjvdatagen\kjvdatagen book JOSH   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_06_JOSH.csv
..\kjvdatagen\kjvdatagen book JUDG   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_07_JUDG.csv
..\kjvdatagen\kjvdatagen book RUTH   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_08_RUTH.csv
..\kjvdatagen\kjvdatagen book 1SAM   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_09_SAM1.csv
..\kjvdatagen\kjvdatagen book 2SAM   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_10_SAM2.csv
..\kjvdatagen\kjvdatagen book 1KGS   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_11_KGS1.csv
..\kjvdatagen\kjvdatagen book 2KGS   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_12_KGS2.csv
..\kjvdatagen\kjvdatagen book 1CHR   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_13_CHR1.csv
..\kjvdatagen\kjvdatagen book 2CHR   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_14_CHR2.csv
..\kjvdatagen\kjvdatagen book EZRA   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_15_EZRA.csv
..\kjvdatagen\kjvdatagen book NEH    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_16_NEH.csv
..\kjvdatagen\kjvdatagen book ESTH   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_17_ESTH.csv
..\kjvdatagen\kjvdatagen book JOB    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_18_JOB.csv
..\kjvdatagen\kjvdatagen book PS     < ..\text\complete\SW1769Bible_both.txt >data\BOOK_19_PS.csv
..\kjvdatagen\kjvdatagen book PROV   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_20_PROV.csv
..\kjvdatagen\kjvdatagen book ECCL   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_21_ECCL.csv
..\kjvdatagen\kjvdatagen book SONG   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_22_SONG.csv
..\kjvdatagen\kjvdatagen book ISA    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_23_ISA.csv
..\kjvdatagen\kjvdatagen book JER    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_24_JER.csv
..\kjvdatagen\kjvdatagen book LAM    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_25_LAM.csv
..\kjvdatagen\kjvdatagen book EZEK   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_26_EZEK.csv
..\kjvdatagen\kjvdatagen book DAN    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_27_DAN.csv
..\kjvdatagen\kjvdatagen book HOS    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_28_HOS.csv
..\kjvdatagen\kjvdatagen book JOEL   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_29_JOEL.csv
..\kjvdatagen\kjvdatagen book AMOS   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_30_AMOS.csv
..\kjvdatagen\kjvdatagen book OBAD   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_31_OBAD.csv
..\kjvdatagen\kjvdatagen book JONAH  < ..\text\complete\SW1769Bible_both.txt >data\BOOK_32_JONAH.csv
..\kjvdatagen\kjvdatagen book MIC    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_33_MIC.csv
..\kjvdatagen\kjvdatagen book NAH    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_34_NAH.csv
..\kjvdatagen\kjvdatagen book HAB    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_35_HAB.csv
..\kjvdatagen\kjvdatagen book ZEPH   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_36_ZEPH.csv
..\kjvdatagen\kjvdatagen book HAG    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_37_HAG.csv
..\kjvdatagen\kjvdatagen book ZECH   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_38_ZECH.csv
..\kjvdatagen\kjvdatagen book MAL    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_39_MAL.csv
..\kjvdatagen\kjvdatagen book MATT   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_40_MATT.csv
..\kjvdatagen\kjvdatagen book MARK   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_41_MARK.csv
..\kjvdatagen\kjvdatagen book LUKE   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_42_LUKE.csv
..\kjvdatagen\kjvdatagen book JOHN   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_43_JOHN.csv
..\kjvdatagen\kjvdatagen book ACTS   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_44_ACTS.csv
..\kjvdatagen\kjvdatagen book ROM    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_45_ROM.csv
..\kjvdatagen\kjvdatagen book 1COR   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_46_COR1.csv
..\kjvdatagen\kjvdatagen book 2COR   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_47_COR2.csv
..\kjvdatagen\kjvdatagen book GAL    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_48_GAL.csv
..\kjvdatagen\kjvdatagen book EPH    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_49_EPH.csv
..\kjvdatagen\kjvdatagen book PHIL   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_50_PHIL.csv
..\kjvdatagen\kjvdatagen book COL    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_51_COL.csv
..\kjvdatagen\kjvdatagen book 1THESS < ..\text\complete\SW1769Bible_both.txt >data\BOOK_52_THESS1.csv
..\kjvdatagen\kjvdatagen book 2THESS < ..\text\complete\SW1769Bible_both.txt >data\BOOK_53_THESS2.csv
..\kjvdatagen\kjvdatagen book 1TIM   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_54_TIM1.csv
..\kjvdatagen\kjvdatagen book 2TIM   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_55_TIM2.csv
..\kjvdatagen\kjvdatagen book TITUS  < ..\text\complete\SW1769Bible_both.txt >data\BOOK_56_TITUS.csv
..\kjvdatagen\kjvdatagen book PHLM   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_57_PHLM.csv
..\kjvdatagen\kjvdatagen book HEB    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_58_HEB.csv
..\kjvdatagen\kjvdatagen book JAS    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_59_JAS.csv
..\kjvdatagen\kjvdatagen book 1PET   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_60_PET1.csv
..\kjvdatagen\kjvdatagen book 2PET   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_61_PET2.csv
..\kjvdatagen\kjvdatagen book 1JOHN  < ..\text\complete\SW1769Bible_both.txt >data\BOOK_62_JOHN1.csv
..\kjvdatagen\kjvdatagen book 2JOHN  < ..\text\complete\SW1769Bible_both.txt >data\BOOK_63_JOHN2.csv
..\kjvdatagen\kjvdatagen book 3JOHN  < ..\text\complete\SW1769Bible_both.txt >data\BOOK_64_JOHN3.csv
..\kjvdatagen\kjvdatagen book JUDE   < ..\text\complete\SW1769Bible_both.txt >data\BOOK_65_JUDE.csv
..\kjvdatagen\kjvdatagen book REV    < ..\text\complete\SW1769Bible_both.txt >data\BOOK_66_REV.csv
