#! /bin/bash

#echo --signing frameworks--
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/Frameworks/QtCore.framework
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/Frameworks/QtGui.framework
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/Frameworks/QtNetwork.framework
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/Frameworks/QtPrintSupport.framework
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/Frameworks/QtSql.framework
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/Frameworks/QtWidgets.framework
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/Frameworks/QtXml.framework

#echo --signing plugins--
#echo accessibility:
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/accessible/libqtaccessiblewidgets.dylib
#echo imageformats:
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqdds.dylib
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqgif.dylib
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqicns.dylib
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqico.dylib
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqjp2.dylib
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqjpeg.dylib
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqmng.dylib
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqtga.dylib
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqtiff.dylib
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqwbmp.dylib
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/imageformats/libqwebp.dylib
#echo platforms:
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/platforms/libqcocoa.dylib
#echo printsupport:
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/printsupport/libcocoaprintersupport.dylib
#echo sqldrivers:
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/sqldrivers/libqsqlite.dylib
#echo styles:
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app/Contents/PlugIns/styles/libqplastiquestyle.dylib

#echo --signing app--
#codesign --force --verify --verbose --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app

echo --signing app--
codesign --force --deep --verify --sign "Developer ID Application: Donna Whisnant" KingJamesPureBibleSearch.app

echo --verifying--
codesign -vvv -d KingJamesPureBibleSearch.app

