######################################################################
# Automatically generated by qmake (2.00a) Fri Aug 12 10:35:00 2005
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .
QT += qt3support

# Input
HEADERS += ColorWidget.h Q4puGenericSignalSpy.h
SOURCES += ColorWidget.cpp main.cpp Q4puGenericSignalSpy.cpp
TARGET = spy
